color = ""

[default]
  device_name = "HAL"
  test_mode_api_key = "sk_test_51HWRcsHNw6dsyxqXcneEGqzMOnn3NxvuQ1pw98EOWCeO8oNB3QPLuhfa6WiwJm6nnb9DapxqwlUKq44Am70Y9Ddc00cbhvWYLcsk_test_51HWRcsHNw6dsyxqXcneEGqzMOnn3NxvuQ1pw98EOWCeO8oNB3QPLuhfa6WiwJm6nnb9DapxqwlUKq44Am70Y9Ddc00cbhvWYLcsk_test_51HWRcsHNw6dsyxqXcneEGqzMOnn3NxvuQ1pw98EOWCeO8oNB3QPLuhfa6WiwJm6nnb9DapxqwlUKq44Am70Y9Ddc00cbhvWYLcsk_test_51HWRcsHNw6dsyxqXcneEGqzMOnn3NxvuQ1pw98EOWCeO8oNB3QPLuhfa6WiwJm6nnb9DapxqwlUKq44Am70Y9Ddc00cbhvWYLc"
