repos:
 -  repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
 - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
   rev: v9.5.0
   hooks:
      - id: commitlint
        stages: [commit-msg]
 -  repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types: [json, yaml, toml, markdown, makefile]
 - repo: https://github.com/pre-commit/mirrors-mypy
   rev: v1.2.0
   hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
      files: ^(src/)
 - repo: https://github.com/python-poetry/poetry
   rev: 1.4.2
   hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
 - repo: local
   hooks:
     - id: black
       name: black
       entry: black
       language: system
       types: [ python ]
       files: ^(src/)
     - id: isort
       name: isort
       entry: isort
       language: system
       args: ['--profile=black']
     - id: flake8
       name: flake8
       entry: flake8
       language: system
       types: [ python ]
       files: ^(src/)
     - id: pydocstyle
       name: pydocstyle
       entry: pydocstyle
       language: system
       args: ['--convention=google', '--add-ignore=D100,D101,D102,D103,D104,D105,D106,D107']
