repos:
 -  repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
 - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
   rev: v9.5.0
   hooks:
      - id: commitlint
        additional_dependencies: ["@commitlint/config-conventional"]
        stages: [commit-msg]
 -  repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1  # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        types: [json, yaml, toml]
 - repo: https://github.com/pre-commit/mirrors-mypy
   rev: v0.800
   hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
      files: ^(src/)
 - repo: https://github.com/python-poetry/poetry
   rev: 1.4.2  # add version here
   hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt"]
 - repo: local
   hooks:
     - id: black
       name: black
       entry: black
       language: system
       types: [ python ]
       files: ^(src/)
     - id: isort
       name: isort
       entry: isort
       args: ['--profile=black']
     - id: flake8
       name: flake8
       entry: flake8
       language: system
       types: [ python ]
       files: ^(src/)
     - id: pydocstyle
       name: pydocstyle
       entry: pydocstyle
       args: ['--convention=google', '--add-ignore=D100,D101,D102,D103,D104,D105,D106,D107']
